version: '3.8'
services:
  # Run the postgres server 
  badger_db:
    image: postgres:13.2
    container_name: badger_db
    restart: always
    environment:
      POSTGRES_PASSWORD: badger
      POSTGRES_USER: badger
      POSTGRES_DB: badger
    volumes:
      - ./database:/var/lib/postgresql/data
    hostname: badger_db
    ports:
      - '5432:5432'
  # Run the badger server
  web:
    container_name: badger_server
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - '8000:8000'
    env_file:
    - .env
    volumes:
      - .:/code
    depends_on:
      - badger_db
    links:
      - badger_db